### PR TITLE
Fix m1n1 wiki link

### PR DESCRIPTION
**Pull request by gpanders**
As far as I can tell this is the best replacement for the (now dead) link. If there is a better wiki page to link to, let me know.

### CODE REVIEW

**Comment by marcan** [comment]
Please signoff your commit :)

**Comment by gpanders** [comment]
Done, sorry about that :)

**Comment by marcan** [comment]
The link you used is also somewhat obsolete, this one is probably better these days as something to link from here: https://github.com/AsahiLinux/docs/wiki/m1n1%3AUser-Guide

**Comment by gpanders** [comment]
Updated the link

**Comment by marcan** [comment]
Thanks!

**Pull request merged**
