### PR TITLE
hv/trace_isp.py: add ISP tracer

### PR DESCRIPTION
**Pull request by kellermanrivero**
Image Signal Processor is a co-processor in charge of Facetime camera
in Apple laptops. This tracer is based on ISP found in M1 processor.

The ISP in M1 SoC exposes seven inter-process communication channels.
Using those channels Application Processor (AP) can perform a variety of
task in the ISP and viceversa. All channels seems to be bidirectional, with
unique exception of TERMINAL channel.

DART translation is used often to translate control structures passed
over IPC channels to IO virtual addresses.

How those channels are used is still unclear but tracer should allow us
to dive deep on high-level protocol to communicate with Facetime camera.
ISP exposes also some I2C peripheral and SPMI registers but I haven't
dive into their working or purpose.

This is early implementation, that mostly dumps ISP internal log buffer and 
memory allocation calls.

### CODE REVIEW

**Comment by marcan** [comment]
Looks good! Don't forget the DCO signoff on the commits :)

**Comment by kellermanrivero** [comment]
@marcan thanks! I'm glad to collaborate. I actually have no idea why it fails DCO check since the commit ends with: 

"Signed-off-by: Kellerman Rivero <krsloco@gmail.com>"

**Comment by marcan** [comment]
If you click on Details it will tell you: the signoff and the commit author differ.

> Commit sha: [8206496](https://github.com/AsahiLinux/m1n1/pull/223/commits/8206496ff2bb1b50a0efc7d56235acd5ac30bba1), Author: Kellerman Rivero, Committer: Kellerman Rivero; Expected "Kellerman Rivero <kellerms@amazon.com>", but got "Kellerman Rivero <krsloco@gmail.com>".

**Comment by kellermanrivero** [comment]
@marcan sorry for the delay. I'm resurrecting this (assuming m1n1 hasn't changed too much that can be actually merged). I will resume work on this.

**Comment by kellermanrivero** [comment]
Hi @marcan, anything I need to do on my side to get this merged? thanks in advance.

**Comment by marcan** [comment]
Sorry for the delay, this one dropped off my radar.

**Comment by kellermanrivero** [comment]
Thanks! no worries.

**Pull request merged**
