### PR TITLE
Cosmetic fixes, avoid relying on UTRSTAT_RXD == 1

### PR DESCRIPTION
**Pull request by pipcet**
Tiny readability fixes. If you don't want this kind of fix, please let me know, but at least this hunk:

```
-    return read32(UART_BASE + UTRSTAT) & UTRSTAT_RXD;
+    return (read32(UART_BASE + UTRSTAT) & UTRSTAT_RXD) ? 1 : 0;
```

seems important to me to make the code more obviously correct.

### CODE REVIEW

**Comment by marcan** [comment]
Can you prefix your commit description with `hv_vuart: `? I did it for your other PR, but please try to keep with the commit message style. It makes it much easier to look for relevant commits.

**Comment by pipcet** [comment]
Sure, sorry, and sorry for the dumb question, but the prefixes are "logical", then, and not directly related to where the modified code lives? Because this PR doesn't touch the hv_uart code, of course.

**Comment by marcan** [comment]
Sorry, that was a brain fart. I meant `uart: `. `hv_vuart` was for the other PR.

**Comment by marcan** [comment]
Actually, I see you touched more things. In that case the commit description is not correct, since it only mentions the uart change. You should write something that encompasses all the changes.

**Pull request merged**
