### PR TITLE
clk: Set up LEAP/PDM clocks

### PR DESCRIPTION
**Pull request by povik**

### CODE REVIEW

**Comment by povik** [comment]
Not sure how to make clang format do something sane with the clk_data structs, so this is not fully clang-formatted.

**Comment by marcan** [comment]
Try putting a comma after the last element of the arrays. If that doesn't do something sane, just use `// clang-format off` and `// clang-format on` around them :)

**Comment by marcan** [comment]
I think this just needs the clang-format fix to go in.

**Comment by povik** [comment]
Ah, thought I pushed the format fix already. Indeed inserting a comma did the trick.

**Pull request merged**
