### PR TITLE
Bit of audio

### PR DESCRIPTION
**Pull request by povik**
This is the code from a paste I posted earlier (https://gist.github.com/povik/66f69f539905bcde6f4cacbae1d24ad6) after some additional care.

(I will be happy to add sign offs once it's specified somewhere what those sign offs mean. :) )

### CODE REVIEW

**Comment by povik** [comment]
If the sign-offs mean this then here they are: https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

**Comment by marcan** [comment]
Indeed we use the same DCO as Linux. We should probably add that to the README...

**Comment by marcan** [comment]
Thanks! :)

I'm curious, are you interested in looking into writing a Linux driver for this? Audio has been on my list for right after the GPU gets on track, but with this much already figured out making an ASoC driver should be fairly easy. I'm happy to take care of it, but if you're interested feel absolutely free to go ahead too! It would be really cool to have basic audio working in the following month or two.

**Comment by povik** [comment]
I am interested! I do not know how much time I will have, but I would definitely like to give it a try. Although if it happens that you or someone else steps in and gets it working in Linux before me, I wouldn't mind at all.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
